
name: Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node 18 & Build Contract
      uses: actions/setup-node@v4
      with:
          node-version: 18.16.0
    - run: yarn install
    - run: yarn build
    - name: Deploy Contract
      run: yarn deploy
